# Generated by Django 2.2.1 on 2019-05-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
